server:
  port: 9090
  servlet:
    context-path: /

spring:
  # 데이터베이스 설정 (다중 DB 바인딩용 커스텀 프로퍼티)
  datasource:
      url: jdbc:postgresql://localhost:5432/recipe
      username: postgres
      password: "1234"
      driver-class-name: org.postgresql.Driver 

  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  ai:
    google:
      genai:
        api-key: ${GEN_KEY}
        project-id: gen-lang-client-0122754073
        location: us-central1
        embedding:
          api-key: ${GEN_KEY}
          project-id: gen-lang-client-0122754073
          text: 
            options:
              model: gemini-embedding-001
              dimensions: 768
      model: 
        embedding:
          text: google-genai

# MyBatis 설정
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: 
    - classpath:/mapper/postgres/*.xml
  configuration:
    map-underscore-to-camel-case: true
